###################################
# Build and publish image to GHCR #
###################################

name: CI
on:
  push:
    branches: [main, pgschk-patch-1]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [main, pgschk-patch-1]
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build mqtt-load-generator
        run: docker build . --tag ghcr.io/pgschk/mqtt-load-generator:latest

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish mqtt-load-generator to GHCR
        run: docker push ghcr.io/pgschk/mqtt-load-generator:latest
